// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcvYYe-FH40fMLqIWD0vKqJbra0j4KCQ',
    appId: '1:179094556335:web:736ce2de44a46de0070e5a',
    messagingSenderId: '179094556335',
    projectId: 'versity-app-backend',
    authDomain: 'versity-app-backend.firebaseapp.com',
    storageBucket: 'versity-app-backend.firebasestorage.app',
    measurementId: 'G-M1QTJTRKHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OEVHsN6ENtaht5yHxKyxCRb29_ncLT8',
    appId: '1:179094556335:android:3c822beb1dfd251b070e5a',
    messagingSenderId: '179094556335',
    projectId: 'versity-app-backend',
    storageBucket: 'versity-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkxRZHcmM3P0QFBzvKuKJ-DcrmF3TTIxw',
    appId: '1:179094556335:ios:6742e7c34ddf7200070e5a',
    messagingSenderId: '179094556335',
    projectId: 'versity-app-backend',
    storageBucket: 'versity-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.versitySoko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkxRZHcmM3P0QFBzvKuKJ-DcrmF3TTIxw',
    appId: '1:179094556335:ios:6742e7c34ddf7200070e5a',
    messagingSenderId: '179094556335',
    projectId: 'versity-app-backend',
    storageBucket: 'versity-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.versitySoko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVcvYYe-FH40fMLqIWD0vKqJbra0j4KCQ',
    appId: '1:179094556335:web:fa7024fd12759f86070e5a',
    messagingSenderId: '179094556335',
    projectId: 'versity-app-backend',
    authDomain: 'versity-app-backend.firebaseapp.com',
    storageBucket: 'versity-app-backend.firebasestorage.app',
    measurementId: 'G-6BF44CV3SW',
  );
}
